server:
  port:8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/moroccan_hotel_db
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Akram2005@
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      format_sql: true
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
      file-size-threshold: 2KB

